STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS:
  - Bf:
    Min: 5.0
    Max: 30.0
  - Cf:
    Min: 0.5
    Max: 2.0
  - Df:
    Min: 100.0
    Max: 10000.0
  - Ef:
    Min: -2.0
    Max: 0.0
  - Br:
    Min: 5.0
    Max: 30.0
  - Cr:
    Min: 0.5
    Max: 2.0
  - Dr:
    Min: 100.0
    Max: 10000.0
  - Er:
    Min: -2.0
    Max: 0.0
  - Cm1:
    Min: 100.0
    Max: 10000.0  
  - Cm2:
    Min: 0.0
    Max: 1.0
  - Cr0:
    Min: 0.1
    Max: 1.4
  - Cr2:
    Min: 0.1
    Max: 1.0
  - Iz: 
    Min: 500.0
    Max: 2000.0
  - Shf:
    Min: -0.02
    Max: 0.02
  - Svf: 
    Min: -300.0
    Max: 300.0
  - Shr:
    Min: -0.02
    Max: 0.02
  - Svr:
    Min: -300.0
    Max: 300.0
VEHICLE_SPECS:
  lf: 1.248
  lr: 1.7328
  mass: 790.0
  h_cg : 0.28 # added by me 

MODEL:
  NAME: lePAVD_iac
  HORIZON: 12
  LAYERS:
    - GRU:
      OUT_FEATURES: 144
      LAYERS: 5
    - BATCHNORM:
    - DENSE:
      OUT_FEATURES: 184
      ACTIVATION: Mish
    - BATCHNORM:
    - DENSE:
      OUT_FEATURES: 184
      ACTIVATION: Mish

  OPTIMIZATION:
    LOSS: MSE  # switching from Huber to MSE for sub-micro error targeting
    BATCH_SIZE: 128  # smaller batch size helps with noise reduction
    NUM_EPOCHS: 3500 # more epochs to allow better convergence
    OPTIMIZER: Adam
    LR: 0.001  # reduced learning rate for high-precision fitting
    GRAD_CLIP: 3.5 # tighter clip for stability
    LR_SCHEDULER: CosineWarmup #CosineAnnealingLR
    DECAY_STEPS: 7500
